- label: Welcome
  path: /docs/
  isHeader: false

- label: Installing the Publisher Theme
  path: /docs/installation
  isHeader: false

- label: Theme Options
  path: /docs/theme-options
  isHeader: false

- label: Theme Customization
  path: /docs/theme-customization
  isHeader: false

- label: Menu Configuration
  path: /docs/menu-configuration
  isHeader: false

- label: Component Shadowing
  path: /docs/component-shadowing
  isHeader: false

- label: Publishing to Netlify
  path: /docs/publishing
  isHeader: false

